import { useState, useMemo } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { AppLayout } from '@/components/layout/AppLayout';
import { StatCard } from '@/components/ui/stat-card';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useTrainerData } from '@/hooks/useMemberData';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { buildPayslipPdf, downloadBlob } from '@/utils/pdfBlob';
import { useBrandContext } from '@/lib/brand/useBrandContext';
import { fetchPayrollSettings } from '@/services/hrmService';
import {
  Wallet, TrendingUp, Calendar, DollarSign, CheckCircle,
  Clock, AlertCircle, User, Download, FileText
} from 'lucide-react';
import { format, startOfMonth, endOfMonth, subMonths } from 'date-fns';
import { Loader2 } from 'lucide-react';

export default function TrainerEarnings() {
  const { profile, user } = useAuth();
  const { trainer, isLoading: trainerLoading } = useTrainerData();
  const [selectedMonth, setSelectedMonth] = useState(0);

  const monthDate = subMonths(new Date(), selectedMonth);
  const monthStart = startOfMonth(monthDate).toISOString();
  const monthEnd = endOfMonth(monthDate).toISOString();
  const monthKey = format(monthDate, 'yyyy-MM');

  // Fetch HR Settings (PF/ESI/PT gating)
  const { data: hrSettings } = useQuery({
    queryKey: ['hr-settings', trainer?.branch_id],
    queryFn: () => fetchPayrollSettings(trainer?.branch_id),
    enabled: !!trainer,
  });

  // Fetch official payroll item for the month (if generated by management)
  const { data: officialPayroll, isLoading: officialLoading } = useQuery({
    queryKey: ['official-payroll', user?.id, monthKey],
    enabled: !!user?.id,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('payroll_items')
        .select(`
          *,
          payroll_runs!inner(period_start, period_end, status)
        `)
        .eq('user_id', user!.id)
        .gte('payroll_runs.period_start', monthStart.split('T')[0])
        .lte('payroll_runs.period_end', monthEnd.split('T')[0])
        .maybeSingle();

      if (error) return null;
      return data;
    },
  });

  // Fetch completed sessions for the month
  const { data: completedSessions = [], isLoading: sessionsLoading } = useQuery({
    queryKey: ['trainer-completed-sessions', trainer?.id, selectedMonth],
    enabled: !!trainer,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('pt_sessions')
        .select(`
          *,
          member_pt_package:member_pt_packages(member:members(member_code, user_id), package:pt_packages(name)),
          trainer:trainers(id, user_id)
        `)
        .eq('trainer_id', trainer!.id)
        .eq('status', 'completed')
        .gte('scheduled_at', monthStart)
        .lte('scheduled_at', monthEnd)
        .order('scheduled_at', { ascending: false });

      if (error) throw error;

      const userIds = (data || []).map((s: any) => s.member_pt_package?.member?.user_id).filter(Boolean);
      let profilesMap: Record<string, string> = {};
      if (userIds.length > 0) {
        const { data: profiles } = await supabase.from('profiles').select('id, full_name').in('id', [...new Set(userIds)]);
        profilesMap = (profiles || []).reduce((acc: Record<string, string>, p: any) => { acc[p.id] = p.full_name || ''; return acc; }, {});
      }

      return (data || []).map((s: any) => ({
        ...s,
        _member_name: s.member_pt_package?.member?.user_id ? profilesMap[s.member_pt_package.member.user_id] : s.member_pt_package?.member?.member_code || 'Unknown',
        _member_code: s.member_pt_package?.member?.member_code,
        _package_name: s.member_pt_package?.package?.name,
      }));
    },
  });

  // Fetch trainer commissions
  const { data: commissions = [] } = useQuery({
    queryKey: ['trainer-commissions', trainer?.id, selectedMonth],
    enabled: !!trainer,
    queryFn: async () => {
      try {
        const { data, error } = await supabase
          .from('trainer_commissions')
          .select('*')
          .eq('trainer_id', trainer!.id)
          .gte('release_date', monthStart.split('T')[0])
          .lte('release_date', monthEnd.split('T')[0])
          .order('release_date', { ascending: false });

        if (error) return [];
        return data || [];
      } catch {
        return [];
      }
    },
  });

  // Sync attendance for pro-rata calculation
  const { data: attendance = [] } = useQuery({
    queryKey: ['trainer-attendance', user?.id, selectedMonth],
    enabled: !!user?.id,
    queryFn: async () => {
      const { data } = await supabase
        .from('staff_attendance')
        .select('shift_date')
        .eq('user_id', user!.id)
        .gte('shift_date', monthStart.split('T')[0])
        .lte('shift_date', monthEnd.split('T')[0]);
      
      const uniqueDays = new Set((data || []).map(a => a.shift_date));
      return Array.from(uniqueDays);
    },
  });

  const sessionRate = trainer?.hourly_rate || 500;
  const totalSessionsCompleted = completedSessions.length;
  const estimatedCommission = totalSessionsCompleted * sessionRate;
  const totalCommissions = commissions.reduce((sum: number, c: any) => sum + (c.amount || 0), 0);
  const baseSalary = Number((trainer as any)?.fixed_salary || 0);

  // Pro-rata Calculation
  const totalDaysInMonth = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0).getDate();
  const daysPresent = attendance.length;
  const proRatedBase = Math.round((baseSalary / totalDaysInMonth) * daysPresent);
  
  // Gated Statutory Deductions
  const pfDeduction = hrSettings?.pf_enabled ? Math.round(proRatedBase * (hrSettings.pf_employee_pct / 100)) : 0;
  const esiDeduction = hrSettings?.esi_enabled ? Math.round((proRatedBase + estimatedCommission + totalCommissions) * (hrSettings.esi_employee_pct / 100)) : 0;
  
  const estimatedNet = proRatedBase + estimatedCommission + totalCommissions - pfDeduction - esiDeduction;

  const isLoading = trainerLoading || sessionsLoading || officialLoading;
  const { data: brand } = useBrandContext((trainer as any)?.branch_id || null);

  const handleDownloadOfficialPayslip = () => {
    if (!officialPayroll || !brand) return;
    
    // Safety check for metadata stored in JSONB if raw columns are missing (though we verified they exist in psql)
    const att: any = officialPayroll.calc_attendance || {};
    
    const blob = buildPayslipPdf({
      employee_name: profile?.full_name || 'Trainer',
      employee_code: (trainer as any)?.employee_code || trainer.id.slice(0, 8),
      designation: 'Personal Trainer',
      period_label: format(monthDate, 'MMMM yyyy'),
      period_start: monthStart.split('T')[0],
      period_end: monthEnd.split('T')[0],
      attendance: { 
        present: Number(att.present || officialPayroll.days_present || daysPresent), 
        payable_days: Number(att.payable_days || officialPayroll.payable_days || daysPresent), 
        total_days: totalDaysInMonth, 
        monthly_salary: Number(officialPayroll.calc_base || baseSalary) 
      },
      earnings: { 
        base: Number(officialPayroll.final_base || proRatedBase), 
        pt_commission: Number(officialPayroll.final_pt_commission || estimatedCommission) + Number(officialPayroll.final_bonus || totalCommissions), 
        ot: Number(officialPayroll.final_ot || 0), 
        bonus: 0 
      },
      deductions: { 
        deductions: Number(officialPayroll.final_deductions || (pfDeduction + esiDeduction)), 
        advance: Number(officialPayroll.final_advance || 0), 
        penalty: Number(officialPayroll.final_penalty || 0) 
      },
      gross: Number(officialPayroll.final_gross || (proRatedBase + estimatedCommission + totalCommissions)),
      net: Number(officialPayroll.final_net || estimatedNet),
    }, brand);
    downloadBlob(blob, `Official_Payslip_${format(monthDate, 'yyyy-MM')}.pdf`);
  };

  if (isLoading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center min-h-[50vh]">
          <Loader2 className="h-8 w-8 animate-spin text-accent" />
        </div>
      </AppLayout>
    );
  }

  if (!trainer) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center min-h-[50vh] gap-4">
          <AlertCircle className="h-12 w-12 text-warning" />
          <h2 className="text-xl font-semibold">No Trainer Profile Found</h2>
          <p className="text-muted-foreground">Your account is not linked to a trainer profile.</p>
        </div>
      </AppLayout>
    );
  }

  const isOfficial = officialPayroll?.status === 'paid';

  return (
    <AppLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
              <Wallet className="h-8 w-8 text-success" />
              My Earnings
            </h1>
            <p className="text-muted-foreground">Pro-rata earnings based on roster and sessions</p>
          </div>
          <div className="flex gap-2">
            {[0, 1, 2].map((monthOffset) => {
              const date = subMonths(new Date(), monthOffset);
              return (
                <Button
                  key={monthOffset}
                  variant={selectedMonth === monthOffset ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setSelectedMonth(monthOffset)}
                >
                  {format(date, 'MMM yyyy')}
                </Button>
              );
            })}
          </div>
        </div>

        {/* Status Indicator */}
        {isOfficial ? (
          <div className="flex items-center gap-2 p-3 bg-success/10 text-success rounded-xl border border-success/20 text-sm">
            <CheckCircle className="h-4 w-4" />
            Payroll for {format(monthDate, 'MMMM')} has been processed. Official payslip is available.
          </div>
        ) : (
          <div className="flex items-center gap-2 p-3 bg-amber-50 text-amber-700 rounded-xl border border-amber-200 text-sm">
            <Clock className="h-4 w-4" />
            Payroll for {format(monthDate, 'MMMM')} is pending management approval. Figures shown are estimates.
          </div>
        )}

        {/* Summary Stats */}
        <div className="grid gap-4 grid-cols-2 md:grid-cols-4">
          <StatCard title="Days Present" value={`${daysPresent}/${totalDaysInMonth}`} icon={Calendar} description="Pro-rata basis" variant="default" />
          <StatCard title="Completed Sessions" value={totalSessionsCompleted} icon={CheckCircle} description={format(monthDate, 'MMMM yyyy')} variant="success" />
          <StatCard title="Estimated Commission" value={`₹${estimatedCommission.toLocaleString()}`} icon={DollarSign} description="Session earnings" variant="accent" />
          <StatCard title="Sales Incentives" value={`₹${totalCommissions.toLocaleString()}`} icon={TrendingUp} description="Package commissions" variant="info" />
        </div>

        {/* Total Earnings Card */}
        <Card className={isOfficial ? "border-success/20 bg-success/5" : "border-amber-200 bg-amber-50/30"}>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">
                  {isOfficial ? 'Net Pay (Official)' : 'Estimated Net (Pro-rata)'} — {format(monthDate, 'MMMM yyyy')}
                </p>
                <p className={`text-4xl font-bold ${isOfficial ? 'text-success' : 'text-amber-700'}`}>
                  ₹{(isOfficial ? officialPayroll.final_net : estimatedNet).toLocaleString()}
                </p>
                <div className="text-xs text-muted-foreground mt-1 flex flex-wrap gap-x-2">
                  <span>Base: ₹{(isOfficial ? officialPayroll.final_base : proRatedBase).toLocaleString()}</span>
                  <span>• Sessions: ₹{(isOfficial ? officialPayroll.final_pt_commission : estimatedCommission).toLocaleString()}</span>
                  {totalCommissions > 0 && <span>• Sales: ₹{totalCommissions.toLocaleString()}</span>}
                  {(pfDeduction > 0 || (officialPayroll?.final_deductions > 0)) && (
                    <span className="text-destructive">
                      • Statutory Deductions: ₹{(isOfficial ? officialPayroll.final_deductions : (pfDeduction + esiDeduction)).toLocaleString()}
                    </span>
                  )}
                </div>
              </div>
              <div className="flex flex-col items-center gap-2">
                <div className={`p-4 rounded-full ${isOfficial ? 'bg-success/10' : 'bg-amber-100'}`}>
                  <FileText className={`h-8 w-8 ${isOfficial ? 'text-success' : 'text-amber-600'}`} />
                </div>
                {isOfficial ? (
                  <Button size="sm" variant="default" onClick={handleDownloadOfficialPayslip}>
                    <Download className="h-4 w-4 mr-1" />
                    Download Payslip
                  </Button>
                ) : (
                  <Button size="sm" variant="outline" disabled className="opacity-50 cursor-not-allowed">
                    <Download className="h-4 w-4 mr-1" />
                    Pending Approval
                  </Button>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Session History */}
        <Card className="border-border/50">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              Completed Sessions — {format(monthDate, 'MMMM yyyy')}
            </CardTitle>
            <CardDescription>Sessions you've completed this month</CardDescription>
          </CardHeader>
          <CardContent>
            {completedSessions.length === 0 ? (
              <div className="text-center py-12">
                <Calendar className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                <p className="text-muted-foreground">No completed sessions this month</p>
              </div>
            ) : (
              <div className="space-y-3">
                {completedSessions.map((session: any) => (
                  <div key={session.id} className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                    <div className="flex items-center gap-4">
                      <div className="p-2 rounded-full bg-success/10">
                        <CheckCircle className="h-5 w-5 text-success" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <User className="h-4 w-4 text-muted-foreground" />
                          <p className="font-medium">
                            {session._member_name || session._member_code || 'Unknown'}
                          </p>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Clock className="h-3 w-3" />
                          <span>{format(new Date(session.scheduled_at), 'EEE, dd MMM • HH:mm')}</span>
                          <span>•</span>
                          <span>{session.duration_minutes} min</span>
                        </div>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="font-semibold text-success">₹{sessionRate}</p>
                      <Badge variant="outline" className="text-xs">
                        {session._package_name || 'Session'}
                      </Badge>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Pro-rata Note */}
        <Card className="border-border/50 bg-muted/30">
          <CardContent className="pt-6">
            <div className="flex items-start gap-4">
              <AlertCircle className="h-5 w-5 text-muted-foreground mt-0.5" />
              <div className="text-sm text-muted-foreground">
                <p className="font-medium mb-1">Payroll Sync & Calculations</p>
                <div className="space-y-2">
                  <p>
                    Earnings are calculated <strong>pro-rata</strong> based on your actual attendance records. Statutory deductions (PF/ESI) honor the active HR configuration for your branch.
                  </p>
                  <p>
                    <strong>Official Payslips:</strong> Only available after payroll is approved and processed by management. Real-time figures are estimates.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
