CREATE TABLE public.web_push_config (id boolean PRIMARY KEY DEFAULT true CHECK (id), public_key text NOT NULL, private_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT ALL ON public.web_push_config TO service_role;
ALTER TABLE public.web_push_config ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.web_push_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, branch_id uuid NOT NULL REFERENCES public.branches(id), endpoint text NOT NULL UNIQUE, p256dh text NOT NULL, auth_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.web_push_subscriptions TO authenticated;
GRANT ALL ON public.web_push_subscriptions TO service_role;
ALTER TABLE public.web_push_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_push_subscriptions ON public.web_push_subscriptions FOR SELECT TO authenticated USING (auth.uid()=user_id);
CREATE TABLE public.web_push_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), notification_id uuid NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE, subscription_id uuid NOT NULL REFERENCES public.web_push_subscriptions(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','failed','suppressed')), attempts integer NOT NULL DEFAULT 0, last_error text, next_attempt_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(notification_id,subscription_id));
GRANT ALL ON public.web_push_deliveries TO service_role;
ALTER TABLE public.web_push_deliveries ENABLE ROW LEVEL SECURITY;
CREATE INDEX web_push_pending_idx ON public.web_push_deliveries(next_attempt_at) WHERE status IN ('pending','sending');
CREATE FUNCTION public.web_push_touch() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
REVOKE ALL ON FUNCTION public.web_push_touch() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER web_push_config_touch BEFORE UPDATE ON public.web_push_config FOR EACH ROW EXECUTE FUNCTION public.web_push_touch();
CREATE TRIGGER web_push_subscriptions_touch BEFORE UPDATE ON public.web_push_subscriptions FOR EACH ROW EXECUTE FUNCTION public.web_push_touch();
CREATE TRIGGER web_push_deliveries_touch BEFORE UPDATE ON public.web_push_deliveries FOR EACH ROW EXECUTE FUNCTION public.web_push_touch();
CREATE FUNCTION public.enqueue_web_push() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,private AS $$ BEGIN INSERT INTO public.web_push_deliveries(notification_id,subscription_id) SELECT NEW.id,s.id FROM public.web_push_subscriptions s WHERE s.user_id=NEW.user_id AND (NEW.branch_id IS NULL OR s.branch_id=NEW.branch_id) ON CONFLICT DO NOTHING; IF FOUND THEN PERFORM private.run_web_push(); END IF; RETURN NEW; EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Browser push enqueue failed'; RETURN NEW; END $$;
REVOKE ALL ON FUNCTION public.enqueue_web_push() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER notifications_enqueue_web_push AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION public.enqueue_web_push();
CREATE FUNCTION public.claim_web_push_deliveries() RETURNS SETOF public.web_push_deliveries LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ UPDATE public.web_push_deliveries SET status='sending',attempts=attempts+1,next_attempt_at=now()+interval '5 minutes' WHERE id IN (SELECT id FROM public.web_push_deliveries WHERE status IN ('pending','sending') AND next_attempt_at<=now() AND attempts<3 ORDER BY created_at LIMIT 30 FOR UPDATE SKIP LOCKED) RETURNING * $$;
REVOKE ALL ON FUNCTION public.claim_web_push_deliveries() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.claim_web_push_deliveries() TO service_role;
CREATE FUNCTION private.run_web_push() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=private,public,extensions AS $$ DECLARE v_url text; v_key text; BEGIN SELECT value INTO v_url FROM private.trigger_config WHERE key='supabase_url'; v_key:=private.mips_service_key(); IF v_url IS NOT NULL AND v_key IS NOT NULL THEN PERFORM net.http_post(url:=v_url||'/functions/v1/web-push',headers:=jsonb_build_object('Content-Type','application/json','Authorization','Bearer '||v_key,'apikey',v_key),body:='{"action":"deliver"}'::jsonb,timeout_milliseconds:=10000); END IF; END $$;
REVOKE ALL ON FUNCTION private.run_web_push() FROM PUBLIC,anon,authenticated;